---
title: "Crecimiento de la mortalidad por Diabetes en México, 20 años de cambios."
author: "JLMR"
date: "2019-03-29"
output: html_document
---


```{r set-global-options, echo=FALSE, message=FALSE, warning=FALSE}
knitr::opts_chunk$set(eval = TRUE, 
                      echo = FALSE, 
                      cache = FALSE,
                      include = TRUE,
                      collapse = FALSE,
                      dependson = NULL,
                      engine = "R", # Chunks will always have R code, unless noted
                      error = FALSE,                      
                      fig.path="Figuras/",  # Set the figure options
                      fig.align = "center", 
                      fig.width = 7,
                      fig.height = 5)
```



```{r silent-packages, echo = FALSE, eval = TRUE, message=FALSE, include = FALSE}

library(foreign)
library(knitr)
library(tidyverse)
library(DT)
library(plotly)
library(grid)
library(gridExtra)
```





```{r, echo = FALSE, fig.width = 8, fig.height = 5  }

library(ggthemes)

growth<-readRDS("tasa_a.rds")%>%
  mutate(fecha=replace(fecha,fecha==99,-1),
         fecha=replace(fecha,fecha==98,-2), 
         fecha=as.numeric(fecha))

ave<-growth%>%
filter(fecha==17)%>%
  group_by(d)%>%
  summarize(ave=mean(rate))


p1<-ggplot(growth, aes(x=fecha,  group=Diabetes, color=Diabetes)) +
geom_line(aes(y=rate))+
facet_wrap(~Estado, nrow=6)+
geom_hline(yintercept = 0, linetype="dashed")+
ylab("Tasa de crecimiento 1998=0 (%)") +
xlab("Año")+
scale_color_manual(values = c('red', "dodgerblue3",""))+
labs(color="")+
theme(legend.position=c(.8,.02))+
scale_x_continuous(breaks=c(0, 5, 10, 15, 17))+
theme_tufte()+
  theme(legend.position="bottom")

p1
```
During the last fifteen years, T2D mortality showed an explosive pattern at the border
states. This growth rate pattern departs from the trend followed by all other death
causes 